### ISSUE TITLE
Activate AppVeyor

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-autocomplete-asciidoc#1]
- https://ci.appveyor.com/team
- https://www.appveyor.com/docs/team-setup

**Comment by ldez** [comment]
@mojavelinux can you manage right access to AppVeyor for the team ?
- https://www.appveyor.com/docs/team-setup
- https://ci.appveyor.com/team

**Comment by mojavelinux** [comment]
I'm on it! :runner:

**Comment by mojavelinux** [comment]
I did not realize AppVeyor had added teams. That's great news!

I need the e-mail address on your AppVeyor account. You can PM me on Twitter if you don't want to post it here.

**Comment by mojavelinux** [comment]
When I add you to a team, it seems that it gives you the option to login with that team using your GitHub account. It's kind of weird that you are logged in as you, but through the team profile. If you login as you, but not through the team profile, then you get a different set of permissions. It works, just kind of tricky.

**Comment by mojavelinux** [comment]
I've activated AppVeyor for this repository. But I still want to get you setup as a Maintainer of that build via the Asciidoctor team.

**Comment by ldez** [comment]
Is it not possible to use GitHub team ?
https://www.appveyor.com/docs/team-setup#github-teams

**Comment by ldez** [comment]
lfernandez.dev@gmail.com

**Comment by mojavelinux** [comment]
For some reason, the only team that is showing up is agents. I'm not sure why. I might have to force sync or something.

**Comment by mojavelinux** [comment]
You are now added. See if you can get the settings page for one of the projects. You might have to logout of AppVeyor, then login again choosing the "asciidoctor" profile.

**Comment by mojavelinux** [comment]
I think the reason we can't add teams has to do with how the team was setup. I setup that team using asciidoctor-docbot. That account is only a member of one team, agents. I can't assign GitHub teams that asciidoctor-docbot is not a member of.

I feel like I'm not smart enough to wrap my head around exactly how AppVeyor modeled this permission system. Either way, adding a collaborator explicitly seems to get the job done.

**Comment by ldez** [comment]
It works !!!
