### ISSUE TITLE
chore: continuous delivery

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-autocomplete-asciidoc#2]
- [x] generated encrypted SSH key
- [x] add Atom Token to Travis UI
- [x] uncomment `.travis.yml`
- [x] change env variable in `.travis/publish.sh`

**Comment by ldez** [comment]
@mojavelinux can you generate the SSH key, add environment variables to `.travis/publish.sh` and add Atom token to Travis UI ?

**Comment by mojavelinux** [comment]
Here I come! :racehorse:

**Comment by mojavelinux** [comment]
All set!

**Comment by ldez** [comment]
yeah !!! :smile:
