### ISSUE TITLE
Autcomplete+ wiki updated!

### ISSUE THREAD

**Issue by nicorikken** [asciidoctor/atom-autocomplete-asciidoc#5]
The [Autocomplete+ wiki](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers) was still showing `asciidoc-preview` as the completion provider.
Not any more: [wiki history](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers/_history)
Please edit if I made any errors / wrong assumptions.

**Comment by ldez** [comment]
Great! It's alright!
