### ISSUE TITLE
Automatic publishing doesn't work.

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-autocomplete-asciidoc#7]
The SSH key is invalid.

@mojavelinux can you generate a encrypted key with new env. variables ?

See https://travis-ci.org/asciidoctor/atom-autocomplete-asciidoc/jobs/132936025

**Comment by mojavelinux** [comment]
Oops! I forgot to add the key to the asciidoctor-docbot profile on GitHub. (Since I deleted it locally, I'll have to regenerate it).

Am I correct in assuming that we will have one SSH key per repository? (and hence multiple SSH keys in the asciidoctor-docbot profile on GitHub).

**Comment by ldez** [comment]
it's more secure to have one key per repository but it's not necessary.

**Comment by mojavelinux** [comment]
That's the confirmation I was looking for. I just wanted to make sure I wasn't doing something wrong.

**Comment by mojavelinux** [comment]
Fingers crossed that works.

**Comment by ldez** [comment]
it's working! :confetti_ball:
