### ISSUE TITLE
tab/shift-tab to indent/un-indent lists items

### ISSUE THREAD

**Issue by metasean** [asciidoctor/atom-autocomplete-asciidoc#9]
I'm not sure if this is the most appropriate place to post this, but it seemed like the most appropriate that I'm aware of.  Please feel free to point me to more appropriate places.

With markdown to indent or un-indent a range of list items a user simply has to select the items and press tab or shift+tab.  Is there a way to do the same with asciidoc in atom?

**Comment by ldez** [comment]
Can you move this issue here: https://github.com/asciidoctor/atom-asciidoc-assistant

Thanks.

**Comment by metasean** [comment]
@ldez - https://github.com/asciidoctor/atom-asciidoc-assistant/issues/14 👍
